export const DEFAULT_PICKS = [
  'The player who last visited Delhi, or who has ever been closest to Delhi, becomes the start player',
  'The player who last visited London, or who has ever been closest to London, becomes the start player',
  'The player who last visited Honolulu, or who has ever been closest to Honolulu, becomes the start player',
  'The player who was born closest to Delhi',
  'The player who was born closest to London',
  'The player who was born closest to Honolulu',
  'The oldest player',
  'The youngest player',
  'The player with the most recent birthday',
  'The player who has been deepest in the sea',
  'The player who last read a history book',
  'The player who carried the heaviest thing today (stomachs do not count)',
  'The player who last held a piece of gold (currently worn jewelry does not count)',
  'The player who most recently rode on a train',
  'The player who most recently rode a bicycle',
  'The player who most recently seen a kung-fu movie',
  'The player who most recently went swimming',
  'The player who most recently ate ice cream',
  'The player who most recently sacrificed something',
  'The player who most recently planted a tree',
  'The player who was last sick',
  'The player who is most north',
  'The player who is most south',
  'The player who is most east',
  'The player who is most we(a)st',
  'The saltiest player',
  'The player who got the most sleep last night',
  'The player who got the least sleep last night',
  'The player who last visited a farm',
  'The player with the shortest email address',
  'The player who last ate bacon',
  'The player who grunts the best',
  'The player who last visited a cave or a cellar',
  'The player with the most unique eyes',
  'The player who last milked a cow',
  'The most suspicious-looking player',
  'The player who has the most facial hair',
  'The player who last travelled for work',
  'The player who last injured themselves',
  'The player who last beat a video game',
  'The player who went first last game',
  'The player who entered the start player command',
  'The player who did the most to setup the game',
  'The player who owns the game',
  'The player who is currently wearing the highest number of unique colors',
  'The player who most recently won a game',
  'The player who most recently went to a sporting event',
  'The player who has the most battery left on their phone',
  'The player who has the least battery left on their phone',
  'Disqualify the last person to arrive to the game, then repeat this command',
  'Disqualify anyone wearing blue, then repeat this command',
  'Disqualify anyone wearing white, then repeat this command',
  "The player who is sitting in the chair that doesn't match the set",
  'The player who last saw a bad movie',
  'The player who last found something shiny',
  'The player who last sent an email',
  'The player who went on a date most recently',
  'The player who has owned the most dogs over the course of their life (owning any product made by Snoop Dogg counts as owning a single dog, and having personally met Snoop Dogg counts as owning all the dogs)',
  'The player who last listened to a Katy Perry song, willingly or otherwise',
  'The player who last hugged a significant other',
  'The player who speaks the most languages (including fictional languages)',
]

export const TAS_PICKS = [
  'The player who last visited Namibia, or who has ever been closest to Namibia, becomes the start player',
  'The player who last visited London, or who has ever been closest to London, becomes the start player',
  "Whoever's been deeper in the sea",
  'The oldest player',
  'The youngest player',
  'The player with the last birthday',
  'The player who last read a history book',
  'The person who carried the heaviest thing today (stomachs do not count)',
  'The start player is the person who last held a piece of gold',
  'Player who has most recently ridden on a train',
  'The last one who rode a bicycle',
  'The last player who has seen a kung-fu movie starts first',
  'The player who was last sick goes first',
  'The player who most recently went swimming',
  'The player who is most north',
  'The player who is most south',
  'The player who is most east',
  'The player who is most we(a)st',
  'The player who was born closest to Austin',
  'The player who was born closest to New York City',
  'The player who was born closest to Seattle',
  'The saltiest player',
  'Whoever had the most sleep last night',
  'Whoever had the least sleep last night',
  'Last to visit a farm',
  'The player who most recently ate ice cream',
  'The player with the shortest email address',
  'The last person to eat bacon',
  'The last person to smell bacon in their office (pick another)',
  'Player who grunts the best',
  'Player who villager hmms the best',
  'Last person to visit a cave or the cellar',
  'The player who proves best able - by general consent - to do a polar bear impression becomes the starting player',
  'The player who most recently sacrificed something',
  'The person with the most unique eyes',
  'Last milked a cow',
  'Most suspicious-looking player',
  'The player who has most recently planted a tree',
  'Whoever has the most facial hair',
  'Last person to travel for work',
  'The player who last injured themselves',
  'The player to last beat a video game',
  'Whoever went first last game',
  'Whoever entered the start player command',
  'Whoever did the most to setup the game',
  'Whoever owns the game',
  'Whoever is currently wearing the highest number of unique colors',
  'Whoever most recently won Twilight Imperium',
  'Whoever most recently went to a sporting event',
  'Whoever has the most battery left on their phone',
  'Whoever has the least battery left on their phone',
  'Disqualify the last person to arrive to lunch, then repeat this command',
  'Disqualify the last person to arrive to lunch, then repeat this command',
  'Disqualify anyone wearing blue, then repeat this command',
  'Disqualify anyone wearing white, then repeat this command',
  'Disqualify anyone who bought lunch, then repeat this command',
  'Disqualify anyone who packed lunch, then repeat this command',
  'The player sitting in the red chair',
  'Last person to see a really bad movie',
  'Last player to find something shiny',
  'Last player to send an email',
  'Last person to watch "The Office"',
  'Last person to go on a date',
  'Kevin, you are the chosen one. If Kevin is not available, the last person to refer to Kevin',
  'The person who has owned the most dogs over the course of their life. Owning any product made by Snoop Dogg counts as owning a single dog. Having personally met Snoop Dogg counts as owning all the dogs. All of them.',
  'The last person to listen to a Katy Perry song. Willingly or otherwise',
  'The last person to hug a significant other',
  'The person who speaks the most languages. Fictional languages count',
]

export const TRAVEL_PICKS = [
  'The player who last visited London. If tied, the player who has traveled closest to London',
  'The player who last visited Paris. If tied, the player who has traveled closest to Paris',
  'The player who last visited Cape Town. If tied, the player who has traveled closest to Cape Town',
  'The player who last visited Istanbul. If tied, the player who has traveled closest to Istanbul',
  'The player who last visited Delhi. If tied, the player who has traveled closest to Delhi',
  'The player who last visited Singapore. If tied, the player who has traveled closest to Singapore',
  'The player who last visited Auckland. If tied, the player who has traveled closest to Auckland',
  'The player who last visited Lima. If tied, the player who has traveled closest to Lima',
  'The player who last visited Honolulu. If tied, the player who has traveled closest to Honolulu',
  'The player who last visited San Francisco. If tied, the player who has traveled closest to San Francisco',
  'The player who last visited Austin. If tied, the player who has traveled closest to Austin',
  'The player who last visited Chicago. If tied, the player who has traveled closest to Chicago',
  'The player who last visited New York. If tied, the player who has traveled closest to New York',
]

export const COIN_FLIP_PICKS = [
  'Heads',
  'Tails',
]
