export const DEFAULT_PICKS = [
    "The player who last visited Delhi, or who has ever been closest to Delhi, becomes the start player",
    "The player who last visited London, or who has ever been closest to London, becomes the start player",
    "The player who last visited Honolulu, or who has ever been closest to Honolulu, becomes the start player",
    "The player who was born closest to Delhi",
    "The player who was born closest to London",
    "The player who was born closest to Honolulu",
    "The oldest player",
    "The youngest player",
    "The player with the most recent birthday",
    "The player who has been deepest in the sea",
    "The player who last read a history book",
    "The player who carried the heaviest thing today (stomachs do not count)",
    "The player who last held a piece of gold (currently worn jewelry does not count)",
    "The player who most recently rode on a train",
    "The player who most recently rode a bicycle",
    "The player who most recently seen a kung-fu movie",
    "The player who most recently went swimming",
    "The player who most recently ate ice cream",
    "The player who most recently sacrificed something",
    "The player who most recently planted a tree",
    "The player who was last sick",
    "The player who is most north",
    "The player who is most south",
    "The player who is most east",
    "The player who is most we(a)st",
    "The saltiest player",
    "The player who got the most sleep last night",
    "The player who got the least sleep last night",
    "The player who last visited a farm",
    "The player with the shortest email address",
    "The player who last ate bacon",
    "The player who grunts the best",
    "The player who last visited a cave or a cellar",
    "The player with the most unique eyes",
    "The player who last milked a cow",
    "The most suspicious-looking player",
    "The player who has the most facial hair",
    "The player who last travelled for work",
    "The player who last injured themselves",
    "The player who last beat a video game",
    "The player who went first last game",
    "The player who entered the start player command",
    "The player who did the most to setup the game",
    "The player who owns the game",
    "The player who is currently wearing the highest number of unique colors",
    "The player who most recently won a game",
    "The player who most recently went to a sporting event",
    "The player who has the most battery left on their phone",
    "The player who has the least battery left on their phone",
    "Disqualify the last person to arrive to the game, then repeat this command",
    "Disqualify anyone wearing blue, then repeat this command",
    "Disqualify anyone wearing white, then repeat this command",
    "The player who is sitting in the chair that doesn't match the set",
    "The player who last saw a bad movie",
    "The player who last found something shiny",
    "The player who last sent an email",
    "The player who went on a date most recently",
    "The player who has owned the most dogs over the course of their life (owning any product made by Snoop Dogg counts as owning a single dog, and having personally met Snoop Dogg counts as owning all the dogs)",
    "The player who last listened to a Katy Perry song, willingly or otherwise",
    "The player who last hugged a significant other.",
    "The player who speaks the most languages (including fictional languages)",
]